blog/urls.py
from django.urls import path
from . import views

app_name = 'blog'
urlpatterns = [
    path('', views.all_blogs, name='all'),
    path('<int:blog_id>/', views.detail, name='detail'),
]

personal_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('blog/', include('blog.urls'), name='blog'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime


class Blog(models.Model):
    title = models.CharField(max_length=100)
    date_time = models.DateTimeField()
    text = models.TextField()

    def __str__(self):
        return self.title

portfolio/models.py
from django.db import models


class Design(models.Model):
    title = models.CharField(max_length=100)
    description = models.CharField(max_length=300)
    image = models.ImageField(upload_to='design/image')
    url = models.URLField(blank=True)

    def __str__(self):
        return self.title

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog


def all_blogs(request):
    blogs_all = Blog.objects.order_by('-date_time')
    return render(request, 'blog/home.html', {'blogs': blogs_all})


def detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    return render(request, 'blog/detail.html', {'id': blog})

portfolio/views.py
from django.shortcuts import render
from .models import Design


def home(request):
    designs = Design.objects.all()
    return render(request, 'portfolio/home.html', context={'des': designs})

blog/templates/blog/detail.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog</title>
    <!-- CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body>
    <div class="container">
        <div class="card">
            <h5 class="card-header">
                {{ id.title }}
            </h5>
            <div class="card-body">
                <h5 class="card-title">
                    <h3>(({{ id.date_time|date:'M/ d/ Y'|upper }}))</h3>
                </h5>
                <p class="card-text">{{ id.text|safe }}</p>
            </div>
        </div>
    </div>
    <!-- JS CDN.... -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
</body>

</html>

blog/templates/blog/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Blog</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <!-- W3 school meta data -->
    <style>
        body {
            background: mediumaquamarine;
        }
    </style>
</head>

<body>
    <!-- NavBar................................................................... -->
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">Alimardani_Blog</a>
            </div>
            <ul class="nav navbar-nav">
                <li class="active"><a href="#">Blog</a></li>
                <li class="dropdown"><a class="dropdown-toggle" data-toggle="dropdown" href="#">Social Media<span
                            class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">Instagram</a></li>
                        <li><a href="#">Facebook</a></li>
                        <li><a href="#">Telegram</a></li>
                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="{% url 'home' %}"><span class="glyphicon glyphicon-home"></span></a></li>

            </ul>
        </div>
    </nav>
    <br>
    <div class="container">
        <!-- content -->
        <h1>Hussein has written {{ blogs.count }} blog{{ blogs.count|pluralize }}</h1>
        <br>
        <!-- things........................................................................... -->
        {% for blog in blogs %}
        <div class="panel panel-default">
            <div class="panel-body">
                <a href="{% url 'blog:detail' blog.id %}">
                    <h1>{{ blog.title }}</h1>
                </a>
                <h2>{{ blog.date_time|date:'M/ d/ Y _ H:i:s'|upper }}</h2>
                <h3>{{ blog.text|striptags|truncatechars:60 }}</h3>
            </div>
        </div>
        <br>
        <hr>
        {% endfor %}
    </div>
</body>

</html>

portfolio/templates/portfolio/home.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <title>Alimardani Blog</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
    <style>
        body {
            background: aquamarine;
        }

        /* Remove the navbar's default margin-bottom and rounded borders */
        .navbar {
            margin-bottom: 0;
            border-radius: 0;
        }

        /* Add a gray background color and some padding to the footer */
        footer {
            background-color: #f2f2f2;
            padding: 25px;
        }
    </style>
</head>

<body>
    <!-- NavBar........................................................................ -->
    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Alimardani</a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul class="nav navbar-nav">
                    <li class="active"><a href="{% url 'blog:all' %}">Blog</a></li>
                    <li><a href="#">About</a></li>
                    <li><a href="#">Gallery</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div class="jumbotron">
        <div class="container text-center">
            <h1>Alimardani Blog</h1>
            <p>Rise and Rise until the the Lambs become Lions</p>
            <img src="{% static 'portfolio/Seljuqs_Eagle.svg.png' %}" alt="" width="200" height="150"
                class="d-inline-block align-top">
        </div>
    </div>
    <div class="container-fluid bg-3 text-center">
        <h3>My favorite serials</h3><br>
        <div class="row">
            {% for design in des %}
            <div class="col-sm-3">
                <div class="thumbnail">
                    <a href="{{ design.url }}"><img src="{{ design.image.url }}" class="img-responsive"
                            style="height: 100%;" alt="Image"></a>

                    <h3>{{ design.title }}</h3>
                    <p>{{ design.description }}</p>
                </div>
            </div>
            {% endfor %}
        </div>
    </div><br>

    <footer class="container-fluid text-center">
        <p>This is a site for people that think they can....</p>
    </footer>

</body>

</html>